# Generated by Django 5.1.4 on 2025-08-27 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAMSSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(blank=True, help_text='Name of the entity/investor', max_length=255, null=True)),
                ('amc_name', models.CharField(blank=True, help_text='Asset Management Company name', max_length=255, null=True)),
                ('folio_number', models.CharField(blank=True, help_text='Folio number', max_length=100, null=True)),
                ('isin', models.CharField(blank=True, help_text='ISIN code', max_length=20, null=True)),
                ('scheme_name', models.TextField(blank=True, help_text='Mutual fund scheme name', null=True)),
                ('closing_unit_balance', models.DecimalField(blank=True, decimal_places=4, help_text='Closing unit balance', max_digits=15, null=True)),
                ('nav', models.DecimalField(blank=True, decimal_places=4, help_text='Current Net Asset Value', max_digits=15, null=True)),
                ('total_cost_value', models.DecimalField(blank=True, decimal_places=4, help_text='Total cost/investment value', max_digits=15, null=True)),
                ('market_value', models.DecimalField(blank=True, decimal_places=4, help_text='Current market value', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cams_summary',
                'ordering': ['-market_value', '-created_at'],
                'indexes': [models.Index(fields=['folio_number'], name='cams_summar_folio_n_09e843_idx'), models.Index(fields=['isin'], name='cams_summar_isin_594eef_idx'), models.Index(fields=['entity_name'], name='cams_summar_entity__09085f_idx')],
                'unique_together': {('folio_number', 'isin')},
            },
        ),
        migrations.CreateModel(
            name='CAMSTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(help_text='Name of the entity/investor', max_length=255)),
                ('amc_name', models.CharField(help_text='Asset Management Company name', max_length=255)),
                ('folio_number', models.CharField(help_text='Folio number', max_length=100)),
                ('isin', models.CharField(help_text='ISIN code', max_length=20)),
                ('scheme_name', models.TextField(help_text='Mutual fund scheme name')),
                ('transaction_date', models.DateField(blank=True, help_text='Date of transaction', null=True)),
                ('transaction_description', models.CharField(blank=True, help_text='Transaction type/description', max_length=255, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=4, help_text='Transaction value', max_digits=15, null=True)),
                ('stamp_duty', models.DecimalField(blank=True, decimal_places=4, help_text='Stamp duty amount', max_digits=15, null=True)),
                ('units', models.DecimalField(blank=True, decimal_places=4, help_text='Number of units', max_digits=15, null=True)),
                ('nav', models.DecimalField(blank=True, decimal_places=4, help_text='Net Asset Value', max_digits=15, null=True)),
                ('unit_balance', models.DecimalField(blank=True, decimal_places=4, help_text='Unit balance after transaction', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cams_transactions',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['folio_number'], name='cams_transa_folio_n_f5b9e1_idx'), models.Index(fields=['isin'], name='cams_transa_isin_60ce2f_idx'), models.Index(fields=['transaction_date'], name='cams_transa_transac_933a5f_idx'), models.Index(fields=['entity_name'], name='cams_transa_entity__0db3e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='CamsPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_no', models.CharField(max_length=20, verbose_name='Folio Number')),
                ('entity_name', models.CharField(max_length=200, verbose_name='Entity Name')),
                ('isin', models.CharField(blank=True, help_text='International Securities Identification Number', max_length=12, null=True, verbose_name='ISIN')),
                ('scheme_name', models.CharField(max_length=200, verbose_name='Scheme Name')),
                ('cost_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cost Value (INR)')),
                ('unit_balance', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Unit Balance')),
                ('nav_date', models.DateField(verbose_name='NAV Date')),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Market Value (INR)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('month', models.IntegerField(blank=True, help_text='1-12', null=True, verbose_name='Month')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CAMS Portfolio',
                'verbose_name_plural': 'CAMS Portfolios',
                'db_table': 'cams_portfolio',
                'indexes': [models.Index(fields=['entity_name'], name='cams_portfo_entity__39a030_idx'), models.Index(fields=['isin'], name='cams_portfo_isin_a05d04_idx'), models.Index(fields=['folio_no'], name='cams_portfo_folio_n_7d4a87_idx'), models.Index(fields=['nav_date'], name='cams_portfo_nav_dat_dea2ba_idx')],
            },
        ),
    ]
