# Generated by Django 5.1.4 on 2025-08-30 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cams_carvy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='camssummary',
            name='cams_summar_folio_n_09e843_idx',
        ),
        migrations.RemoveIndex(
            model_name='camssummary',
            name='cams_summar_isin_594eef_idx',
        ),
        migrations.RemoveIndex(
            model_name='camssummary',
            name='cams_summar_entity__09085f_idx',
        ),
        migrations.RemoveIndex(
            model_name='camstransaction',
            name='cams_transa_folio_n_f5b9e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='camstransaction',
            name='cams_transa_isin_60ce2f_idx',
        ),
        migrations.RemoveIndex(
            model_name='camstransaction',
            name='cams_transa_transac_933a5f_idx',
        ),
        migrations.RemoveIndex(
            model_name='camstransaction',
            name='cams_transa_entity__0db3e9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='camssummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='camssummary',
            name='entry_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='camssummary',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='camstransaction',
            name='entry_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='camstransaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='amc_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='closing_unit_balance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='entity_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='folio_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='isin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='market_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='nav',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='scheme_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='total_cost_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='amc_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='entity_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='folio_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='isin',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='nav',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='scheme_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='stamp_duty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='transaction_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='unit_balance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='units',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
