# Generated by Django 5.1.4 on 2025-08-30 07:13

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cams_carvy', '0002_remove_camssummary_cams_summar_folio_n_09e843_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camssummary',
            name='closing_unit_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='market_value',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='nav',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='total_cost_value',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='nav',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='stamp_duty',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='transaction_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='unit_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='units',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='value',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=15),
        ),
    ]
