# Generated by Django 5.1.4 on 2025-08-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cams_carvy', '0003_alter_camssummary_closing_unit_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camssummary',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='camssummary',
            unique_together={('folio_number', 'isin')},
        ),
        migrations.RemoveField(
            model_name='camstransaction',
            name='entry_hash',
        ),
        migrations.RemoveField(
            model_name='camstransaction',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='camsportfolio',
            name='cost_value',
            field=models.CharField(max_length=50, verbose_name='Cost Value (INR)'),
        ),
        migrations.AlterField(
            model_name='camsportfolio',
            name='market_value',
            field=models.CharField(max_length=50, verbose_name='Market Value (INR)'),
        ),
        migrations.AlterField(
            model_name='camsportfolio',
            name='unit_balance',
            field=models.CharField(max_length=50, verbose_name='Unit Balance'),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='amc_name',
            field=models.CharField(blank=True, help_text='Asset Management Company name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='closing_unit_balance',
            field=models.CharField(blank=True, help_text='Closing unit balance', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='entity_name',
            field=models.CharField(blank=True, help_text='Name of the entity/investor', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='folio_number',
            field=models.CharField(blank=True, help_text='Folio number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='isin',
            field=models.CharField(blank=True, help_text='ISIN code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='market_value',
            field=models.CharField(blank=True, help_text='Current market value', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='nav',
            field=models.CharField(blank=True, help_text='Current Net Asset Value', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='scheme_name',
            field=models.TextField(blank=True, help_text='Mutual fund scheme name', null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='total_cost_value',
            field=models.CharField(blank=True, help_text='Total cost/investment value', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='amc_name',
            field=models.CharField(help_text='Asset Management Company name', max_length=255),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='entity_name',
            field=models.CharField(help_text='Name of the entity/investor', max_length=255),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='folio_number',
            field=models.CharField(help_text='Folio number', max_length=100),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='isin',
            field=models.CharField(help_text='ISIN code', max_length=20),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='nav',
            field=models.CharField(blank=True, help_text='Net Asset Value', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='scheme_name',
            field=models.TextField(help_text='Mutual fund scheme name'),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='stamp_duty',
            field=models.CharField(blank=True, help_text='Stamp duty amount', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='transaction_date',
            field=models.DateField(blank=True, help_text='Date of transaction', null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='transaction_description',
            field=models.CharField(blank=True, help_text='Transaction type/description', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='unit_balance',
            field=models.CharField(blank=True, help_text='Unit balance after transaction', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='units',
            field=models.CharField(blank=True, help_text='Number of units', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='value',
            field=models.CharField(blank=True, help_text='Transaction value', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='camssummary',
            index=models.Index(fields=['folio_number'], name='cams_summar_folio_n_09e843_idx'),
        ),
        migrations.AddIndex(
            model_name='camssummary',
            index=models.Index(fields=['isin'], name='cams_summar_isin_594eef_idx'),
        ),
        migrations.AddIndex(
            model_name='camssummary',
            index=models.Index(fields=['entity_name'], name='cams_summar_entity__09085f_idx'),
        ),
        migrations.AddIndex(
            model_name='camstransaction',
            index=models.Index(fields=['folio_number'], name='cams_transa_folio_n_f5b9e1_idx'),
        ),
        migrations.AddIndex(
            model_name='camstransaction',
            index=models.Index(fields=['isin'], name='cams_transa_isin_60ce2f_idx'),
        ),
        migrations.AddIndex(
            model_name='camstransaction',
            index=models.Index(fields=['transaction_date'], name='cams_transa_transac_933a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='camstransaction',
            index=models.Index(fields=['entity_name'], name='cams_transa_entity__0db3e9_idx'),
        ),
        migrations.RemoveField(
            model_name='camssummary',
            name='entry_hash',
        ),
        migrations.RemoveField(
            model_name='camssummary',
            name='updated_by',
        ),
    ]
