# Generated by Django 5.1.4 on 2025-08-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cams_carvy', '0004_alter_camssummary_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camssummary',
            options={'ordering': ['-market_value', '-created_at']},
        ),
        migrations.AlterField(
            model_name='camsportfolio',
            name='cost_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cost Value (INR)'),
        ),
        migrations.AlterField(
            model_name='camsportfolio',
            name='market_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Market Value (INR)'),
        ),
        migrations.AlterField(
            model_name='camsportfolio',
            name='unit_balance',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Unit Balance'),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='closing_unit_balance',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Closing unit balance', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='market_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Current market value', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='nav',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Current Net Asset Value', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='total_cost_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Total cost/investment value', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='nav',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Net Asset Value', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='stamp_duty',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Stamp duty amount', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='unit_balance',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Unit balance after transaction', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='units',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Number of units', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Transaction value', max_digits=15, null=True),
        ),
    ]
