# Generated by Django 5.1.4 on 2025-08-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cams_carvy', '0005_alter_camssummary_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camssummary',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='camsportfolio',
            name='cost_value',
            field=models.CharField(max_length=50, verbose_name='Cost Value (INR)'),
        ),
        migrations.AlterField(
            model_name='camsportfolio',
            name='market_value',
            field=models.CharField(max_length=50, verbose_name='Market Value (INR)'),
        ),
        migrations.AlterField(
            model_name='camsportfolio',
            name='unit_balance',
            field=models.CharField(max_length=50, verbose_name='Unit Balance'),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='closing_unit_balance',
            field=models.CharField(blank=True, help_text='Closing unit balance', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='market_value',
            field=models.CharField(blank=True, help_text='Current market value', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='nav',
            field=models.CharField(blank=True, help_text='Current Net Asset Value', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camssummary',
            name='total_cost_value',
            field=models.CharField(blank=True, help_text='Total cost/investment value', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='nav',
            field=models.CharField(blank=True, help_text='Net Asset Value', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='stamp_duty',
            field=models.CharField(blank=True, help_text='Stamp duty amount', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='unit_balance',
            field=models.CharField(blank=True, help_text='Unit balance after transaction', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='units',
            field=models.CharField(blank=True, help_text='Number of units', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camstransaction',
            name='value',
            field=models.CharField(blank=True, help_text='Transaction value', max_length=50, null=True),
        ),
    ]
