# Generated by Django 5.1.4 on 2025-08-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cams_carvy', '0006_alter_camssummary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camsportfolio',
            name='entry_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='camssummary',
            name='entry_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='camstransaction',
            name='entry_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
