# Generated by Django 5.1.4 on 2025-08-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cams_carvy', '0007_camsportfolio_entry_hash_camssummary_entry_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camssummary',
            name='nav_date',
            field=models.DateField(blank=True, help_text='Date of nav', null=True),
        ),
    ]
