# Generated by Django 5.1.4 on 2025-08-31 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cams_carvy', '0008_camssummary_nav_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='camssummary',
            unique_together={('folio_number', 'isin', 'entity_name')},
        ),
    ]
