# Generated by Django 5.1.4 on 2025-08-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cams_carvy', '0009_alter_camssummary_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='camssummary',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='camssummary',
            index=models.Index(fields=['amc_name'], name='cams_summar_amc_nam_4f7a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='camssummary',
            index=models.Index(fields=['scheme_name'], name='cams_summar_scheme__b8e631_idx'),
        ),
        migrations.AddIndex(
            model_name='camssummary',
            index=models.Index(fields=['closing_unit_balance'], name='cams_summar_closing_94aa32_idx'),
        ),
        migrations.AddIndex(
            model_name='camssummary',
            index=models.Index(fields=['nav'], name='cams_summar_nav_3d3f06_idx'),
        ),
        migrations.AddIndex(
            model_name='camssummary',
            index=models.Index(fields=['total_cost_value'], name='cams_summar_total_c_e280f4_idx'),
        ),
        migrations.AddIndex(
            model_name='camssummary',
            index=models.Index(fields=['market_value'], name='cams_summar_market__022b84_idx'),
        ),
        migrations.AddIndex(
            model_name='camssummary',
            index=models.Index(fields=['nav_date'], name='cams_summar_nav_dat_ba3fea_idx'),
        ),
        migrations.AddIndex(
            model_name='camstransaction',
            index=models.Index(fields=['amc_name'], name='cams_transa_amc_nam_922dea_idx'),
        ),
        migrations.AddIndex(
            model_name='camstransaction',
            index=models.Index(fields=['scheme_name'], name='cams_transa_scheme__f22432_idx'),
        ),
        migrations.AddIndex(
            model_name='camstransaction',
            index=models.Index(fields=['transaction_description'], name='cams_transa_transac_aafcea_idx'),
        ),
        migrations.AddIndex(
            model_name='camstransaction',
            index=models.Index(fields=['value'], name='cams_transa_value_ade480_idx'),
        ),
        migrations.AddIndex(
            model_name='camstransaction',
            index=models.Index(fields=['stamp_duty'], name='cams_transa_stamp_d_18965d_idx'),
        ),
        migrations.AddIndex(
            model_name='camstransaction',
            index=models.Index(fields=['units'], name='cams_transa_units_7582e7_idx'),
        ),
        migrations.AddIndex(
            model_name='camstransaction',
            index=models.Index(fields=['nav'], name='cams_transa_nav_9c2496_idx'),
        ),
        migrations.AddIndex(
            model_name='camstransaction',
            index=models.Index(fields=['unit_balance'], name='cams_transa_unit_ba_e85255_idx'),
        ),
        migrations.AddConstraint(
            model_name='camssummary',
            constraint=models.UniqueConstraint(fields=('folio_number', 'isin', 'entity_name', 'amc_name', 'scheme_name', 'closing_unit_balance', 'nav', 'total_cost_value', 'market_value', 'nav_date'), name='unique_summary_record'),
        ),
        migrations.AddConstraint(
            model_name='camstransaction',
            constraint=models.UniqueConstraint(fields=('folio_number', 'isin', 'entity_name', 'amc_name', 'scheme_name', 'transaction_date', 'transaction_description', 'value', 'stamp_duty', 'units', 'nav', 'unit_balance'), name='unique_transaction_record'),
        ),
    ]
