# Generated by Django 5.1.4 on 2025-08-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybercellreport',
            name='lien_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cybercellreport',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
