# Generated by Django 5.1.4 on 2025-08-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_app', '0002_cybercellreport_lien_amount_cybercellreport_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybercellreport',
            name='entry_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
